name: "Rollout generated plan"
description: "Rollout Bytebase generated plan for SQL migrations"

inputs:
  bytebase-url:
    description: "Bytebase instance URL"
    default: ""
    required: true
  bytebase-service-account:
    description: "Bytebase service account email"
    default: "bytebase@service.bytebase.com"
    required: false
  bytebase-service-account-secret:
    description: "Bytebase service account secret"
    default: ""
    required: true
  project:
    description: "Bytebase project name e.g. [projects/latitude-demo]"
    default: ""
    required: true
  target-stage:
    description: "Bytebase target stage e.g. [environments/qa]"
    default: ""
    required: true
  full-repo:
    description: "GitHub repository containing the SQL release workflow e.g. [naing2htun/latitude-demo]"
    default: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Get run ID of latest successful run
      id: get-run
      shell: bash
      run: |
        RUN_ID=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ inputs.full-repo }}/actions/workflows/sql-plan.yaml/runs?status=success&branch=main" \
          | jq -r '.workflow_runs[0].id')

        echo "run-id=$RUN_ID" >> $GITHUB_OUTPUT
    - name: Download rollout plan artifact
      id: download-artifact
      uses: actions/download-artifact@v5
      with:
        name: bytebase-plan
        github-token: ${{ secrets.PAT }}
        repository: ${{ inputs.full-repo }}
        run-id: ${{ steps.get-run.outputs.run-id }}
    - name: Rollout to ${{ inputs.target-stage }}
      shell: bash
      run: |
        bytebase-action rollout \
          --url=${{ inputs.bytebase-url }} \
          --service-account=${{ inputs.bytebase-service-account }} \
          --service-account-secret='${{ inputs.bytebase-service-account-secret }}' \
          --project=${{ inputs.project }} \
          --target-stage=${{ inputs.target-stage }} \
          --plan=$(cat ${{ steps.download-artifact.outputs.download-path }}/plan.txt)