name: "Generate rollout plan"
description: "Generate Bytebase rollout plan for SQL migrations"

inputs:
  bytebase-url:
    description: "Bytebase instance URL"
    default: ""
    required: true
  bytebase-service-account:
    description: "Bytebase service account email"
    default: "bytebase@service.bytebase.com"
    required: false
  bytebase-service-account-secret:
    description: "Bytebase service account secret"
    default: ""
    required: true
  project:
    description: "Bytebase project name e.g. [projects/latitude-demo]"
    default: ""
    required: true
  targets:
    description: "Bytebase comma-separated targets e.g. [instances/latitude-qa/databases/latitude-demo-qa,instances/latitude-stg/databases/latitude-demo-stg]"
    default: ""
    required: true
  file-pattern:
    description: "Bytebase glob for migration files"
    default: "migrations/*.up.sql"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Get commit message as title
      id: get-pr-title
      shell: bash
      run: |
        PR_TITLE="${{ github.event.head_commit.message || github.sha }}"
        {
          echo "pr-title<<EOF"
          echo "$PR_TITLE"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        echo "Using title: $PR_TITLE"
    - name: Generate rollout plan
      shell: bash
      run: |
        bytebase-action rollout \
          --url=${{ inputs.bytebase-url }} \
          --service-account=${{ inputs.bytebase-service-account }} \
          --service-account-secret='${{ inputs.bytebase-service-account-secret }}' \
          --project=${{ inputs.project }} \
          --file-pattern="${{ inputs.file-pattern }}" \
          --targets="${{ inputs.targets }}" \
          --release-title="${{ steps.get-pr-title.outputs.pr-title }}" \
          --output=${{ runner.temp }}/bytebase-metadata.json
    - name: Extract plan to file
      id: extract-plan
      shell: bash
      run: |
        jq -r .plan ${{ runner.temp }}/bytebase-metadata.json > ${{ github.workspace }}/plan.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bytebase-plan
        path: ${{ github.workspace }}/plan.txt
        overwrite: true